name: The Future Trends Group
favicon: null
layout_spectrum: 0.8259397780057043
typography_spectrum: 0.4273657549638301
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.24993408285081387
  lightness: 0.9750424297526479
  saturation: 0.9138581028673798
  rhythmicContrast: 0.03239079797640443
purpose: []
