name: The Future Trends Group
favicon: null
layout_spectrum: 0.8259397780057043
typography_spectrum: 0.37966
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#000000'
    - '#2d537d'
    - '#a8abb6'
    - '#b08169'
  brandStrength: 1
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 1
purpose: []
